
name: Push Docker Hub
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_HUB_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Image Push
        run: ./pushDockerHub.sh
