
name: Sample workflow_dispatch
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Image Push
        run: ./pushDockerHub.sh

