name: Sed file
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TEST: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Sed 
        run: |
          sed -i "s|\${TEST}|$TEST|" test-sh/test.sh
          cat test-sh/test.sh
      - name: Show
        run: cat test-sh/test.sh
