name: Deploy to Docker Hub
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Cat Default
        run: cat sample.txt


